CREATE TABLE PERSON (
    PERSON_ID INT AUTO_INCREMENT PRIMARY KEY,
    LAST_NAME VARCHAR(50) NOT NULL,
    FIRST_NAME VARCHAR(50) NOT NULL,
    ZIP_CODE INT(10) NOT NULL,
    CITY VARCHAR(50) NOT NULL,
	PHONE VARCHAR(30) NULL,
	LOCK_TSTMP timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
	UNIQUE KEY uk_person  (PERSON_ID,LAST_NAME, FIRST_NAME, ZIP_CODE, CITY, PHONE)
);
